theme: jekyll-theme-minimal
title: ARG at the ATDC
logo: /assets/img/arg.jpg
description: I'm the Marketing Catalyst (startup coach) at the <a href="http://atdc.org">ATDC</a>. This a collection of the content and projects I've created for the ATDC.
show_downloads: false
